# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageid', models.BigIntegerField(default=0)),
                ('partnerid', models.BigIntegerField(default=0)),
                ('billing', models.CharField(default='', max_length=64)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('current_period_start', models.DateTimeField()),
                ('customer', models.CharField(default='', max_length=64)),
                ('subscription_id', models.CharField(default='', max_length=64)),
                ('subscription_created', models.DateTimeField()),
                ('subscription_item_id', models.CharField(default='', max_length=64)),
                ('plan_amount', models.IntegerField(default=0)),
                ('plan_created', models.DateTimeField()),
                ('plan_currency', models.CharField(default='', max_length=3)),
                ('plan_id', models.CharField(default='', max_length=256)),
                ('plan_interval', models.CharField(default='', max_length=8)),
                ('plan_interval_count', models.IntegerField()),
                ('plan_livemode', models.BooleanField()),
                ('plan_name', models.CharField(default='', max_length=256)),
                ('quantity', models.IntegerField(default=0)),
                ('object_type', models.CharField(default='', max_length=32)),
                ('total_count', models.IntegerField(default=0)),
                ('start', models.DateTimeField()),
                ('status', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
