# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 13:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.BigIntegerField(default=1)),
                ('api_key', models.CharField(default='', max_length=128)),
                ('api_secret', models.CharField(default='', max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.BigIntegerField(default=1)),
                ('api_key', models.CharField(default='', max_length=128)),
                ('api_secret', models.CharField(default='', max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.BigIntegerField(default=0)),
                ('filehash', models.CharField(default='', max_length=128)),
                ('size_unoptimized', models.IntegerField(default=0)),
                ('size_optimized', models.IntegerField(default=0)),
                ('fileurl', models.CharField(default='', max_length=2000)),
                ('filepath', models.CharField(default='', max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencycode', models.CharField(default='', max_length=3)),
                ('currencysymbol', models.CharField(default='', max_length=16)),
                ('zerodecimal', models.BooleanField(default=False)),
                ('packagetype', models.CharField(default='', max_length=32)),
                ('packagename', models.CharField(default='', max_length=256)),
                ('planname', models.CharField(default='', max_length=256)),
                ('planid', models.CharField(default='', max_length=256)),
                ('packagediscount', models.IntegerField(default=0)),
                ('intervalcount', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('quota', models.BigIntegerField(default=0)),
                ('priceoverquota', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnerid', models.BigIntegerField(default=1)),
                ('api_key', models.CharField(default='', max_length=128)),
                ('api_secret', models.CharField(default='', max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField(default=1)),
                ('packageid', models.BigIntegerField(default=0)),
                ('partnerid', models.BigIntegerField(default=0)),
                ('billing', models.CharField(default='', max_length=64)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('current_period_start', models.DateTimeField()),
                ('customer', models.CharField(default='', max_length=64)),
                ('subscription_id', models.CharField(default='', max_length=64)),
                ('subscription_created', models.DateTimeField()),
                ('subscription_item_id', models.CharField(default='', max_length=64)),
                ('plan_amount', models.IntegerField(default=0)),
                ('plan_created', models.DateTimeField()),
                ('plan_currency', models.CharField(default='', max_length=3)),
                ('plan_id', models.CharField(default='', max_length=256)),
                ('plan_interval', models.CharField(default='', max_length=8)),
                ('plan_interval_count', models.IntegerField()),
                ('plan_livemode', models.BooleanField()),
                ('plan_name', models.CharField(default='', max_length=256)),
                ('quantity', models.IntegerField(default=0)),
                ('object_type', models.CharField(default='', max_length=32)),
                ('total_count', models.IntegerField(default=0)),
                ('start', models.DateTimeField()),
                ('status', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UnoptimizedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.BigIntegerField(default=0)),
                ('filehash', models.CharField(default='', max_length=128)),
                ('size_unoptimized', models.IntegerField(default=0)),
                ('fileurl', models.CharField(default='', max_length=2000)),
                ('filepath', models.CharField(default='', max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ispartner', models.BooleanField(default=False)),
                ('partnerid', models.BigIntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('min_subscipitions', models.IntegerField(default=0)),
                ('max_subscipitions', models.IntegerField(default=0)),
                ('about_company', models.CharField(blank=True, max_length=4096, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
