# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_auto_20180113_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispartner', models.BooleanField(default=False)),
                ('partnerid', models.BigIntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('min_subscipitions', models.IntegerField(default=0)),
                ('max_subscipitions', models.IntegerField(default=0)),
                ('about_company', models.CharField(blank=True, max_length=4096, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
