# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='', max_length=128)),
                ('api_secret', models.CharField(default='', max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='', max_length=128)),
                ('api_secret', models.CharField(default='', max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filehash', models.CharField(default='', max_length=128)),
                ('size_unoptimized', models.IntegerField(default=0)),
                ('size_optimized', models.IntegerField(default=0)),
                ('fileurl', models.CharField(default='', max_length=2000)),
                ('filepath', models.CharField(default='', max_length=4096)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencycode', models.CharField(default='', max_length=3)),
                ('currencysymbol', models.CharField(default='', max_length=16)),
                ('zerodecimal', models.BooleanField(default=False)),
                ('packagetype', models.CharField(default='', max_length=32)),
                ('packagename', models.CharField(default='', max_length=256)),
                ('planname', models.CharField(default='', max_length=256)),
                ('planid', models.CharField(default='', max_length=256)),
                ('packagediscount', models.IntegerField(default=0)),
                ('intervalcount', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('quota', models.BigIntegerField(default=0)),
                ('priceoverquota', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='', max_length=128)),
                ('api_secret', models.CharField(default='', max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='UnoptimizedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.BigIntegerField(default=0)),
                ('filehash', models.CharField(default='', max_length=128)),
                ('size_unoptimized', models.IntegerField(default=0)),
                ('fileurl', models.CharField(default='', max_length=2000)),
                ('filepath', models.CharField(default='', max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='administratorcredential',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Customer'),
        ),
    ]
